services:
  WeatherApp-mysql:
    image: mysql:8.0
    container_name: WeatherApp-mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'testuser'
      MYSQL_USER: 'testuser'
      MYSQL_PASSWORD: '310testpw'
      MYSQL_ROOT_PASSWORD: '310rootpw'
    ports:
      - '3306:3306'
    volumes:
      - mysql-db:/var/lib/mysql
      - ./ddl:/docker-entrypoint-initdb.d

  cosc310-sqlserver:
    image: mcr.microsoft.com/azure-sql-edge
    platform: linux/amd64
    container_name: cosc310-sqlserver
    restart: always
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: '310#sa#pw'
    ports:
      - '1433:1433'
    volumes:
      - cosc310-db:/var/opt/mssql
      - ./ddl:/scripts
    entrypoint: ["/bin/bash", "-c", "./scripts/initialize_sql.sh"]

volumes:
  cosc310-db:
  mysql-db: